// "use client";
import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang='en'>
      {/* <Script src="otel.min.js" /> */}
      <Script src="otel.min-without-context.js" />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
